---

- name: Certifikation installation
  hosts: all
  become: true
  tasks:
    - name: Install the ca-certificates package
      yum:
        name: ca-certificates

    - name: Enable the dynamic CA configuration feature
      shell: update-ca-trust force-enable

    - name: Add it as a new file to /etc/pki/ca-trust/source/anchors/
      shell: cp foo.crt /etc/pki/ca-trust/source/anchors/

    - name: Use command
      shell: update-ca-trust extract