---

- name: Change hostname to modified MAC
  hosts: all
  become: true
  tasks:
    - name: Set hostname
      copy:
        src: /var/log/comline/MAC
        dest: /etc/hostname
        

# /var/log/comline/MAC .. auslesen und in set hostname packen