---

- name: Grap MAC Adress
  hosts: all
  pre_tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.interface }} + {{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
    - copy:
        content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.interface }} + {{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
        dest: "/var/log/comline/MACTYPE/"
        