---

- name: Look for NIC and MAC
  hosts: all
  pre_tasks:
    - name: Create directory if not exist
      file:
        path: /var/log/comline/MACTYPE
        state: directory
    - debug:
          msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.interface }} + {{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"