--- # Start Netzwerkkarte identifizieren
- hosts: all
  tasks:
      - name: Check for ENS33
      command: echo "ip l | grep -A 1 ens33 | grep "link/ether" | cut -d " " -f 6 | tr -d ":" | tr "[a-f]" "[A-F]""
      command: echo "ens33 Mac Adresse gefunden"
      command: echo "ens33" >> /var/log/comline/MACTYPE