---

- name: Gather Network Information
  hosts: all
  become: true
  tasks:
    - name: Lookup NIC, create file and paste info
      copy:
              content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.interface }}"
              dest: "/var/log/comline/NIC"

    - name: Lookup MAC, create file and paste info
      copy:
              content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }} | replace('\:', '') | replace('\[a-f]:', '\[A-F]')"
              dest: "/var/log/comline/MAC"

    - name: Lookup IP, create file and paste info
      copy:
              content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
              dest: "/var/log/comline/IP"