---

- name: Lookup NIC&MAC&IP, Paste into file
  hosts: all
  tasks:
    - name: Create directory if not exist
      file:
        path: /var/log/comline/MACTYPE
        state: directory

    - name: Lookup & Create and paste into file
      copy:
              content: " NIC: {{ hostvars[inventory_hostname].ansible_default_ipv4.interface }} + MAC: {{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }} + IP: {{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
              dest: "/var/log/comline/MACTYPE/NicMac.yml"