--- # Start Netzwerkkarte identifizieren
- hosts: all
  tasks:
    - name: Check for ENP2S0
      command: ["ip l | grep -A 1 enp2s0 | grep "link\/ether" | cut -d " " -f 6 | tr -d ":" | tr "[a-f]" "[A-F]""]
      - name: MAC found
        command: ["echo "enp2s0 Mac Adresse gefunden""]
         - name: Store Data
           command: ["echo "enp2s0" >> /var/log/comline/MACTYPE"]