---

- name: Grap MAC Adress
  hosts: all
  pre_tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
        msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.interface }}"