---

- name: Check if NIC is active
  hosts: all
  become: true
  tasks:
    - name: Ouput of hostname with his NIC
      set_fact:
        ansible_eth: "{% set ansible_eth = ansible_eth|default([]) + [hostvars[inventoryhostname]['ansible' + item]] %}{{ ansible_eth|list }}"
      when: hostvars[inventory_hostname]['ansible_' + item]['active'] == true
      with_items: "{{ansible_interfaces}}"