---

- name: CHECK IF NIC IS ACTIVE
  hosts: all
  become: true
  tasks:
    - name: find interface facts
      debug:
        msg: System {{ inventory_hostname }} has interface {{ ansible_default_ipv4.interface }}
  when: ansible_% is "active"