---

- name: CHECK IF NIC IS ACTIVE
  hosts: all
  become: true
  tasks:
    - name: find interface facts
      debug:
        msg: "{{ item }}"
      when: '"active" in item'
      loop: "{{ output.stdout_lines.0 }}"
      