---

- name: Gather Network Information
  hosts: all
  become: true
  tasks:
    - name: Lookup NIC, create file and paste info
      copy:
              content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.interface }}"
              dest: "/var/log/comline/NIC"

    - name: Lookup MAC, create file and paste info in uppercase
      copy:
              content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress|upper }}"
              dest: "/var/log/comline/MAC"

    - name: replacing dots
      replace:
        path: /var/log/comline/MAC
        regexp: ':'
        replace: ""

    - name: Lookup IP, create file and paste info
      copy:
              content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
              dest: "/var/log/comline/IP"